version: '3.8'

services:
  db:
    image: postgres:15
    container_name: imdb-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: imdb
    ports:
      - "5432:5432"
    volumes:
      - imdb_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: imdb-redis
    restart: always
    ports:
      - "6379:6379"

  webapp:
    build: .
    container_name: imdb-api
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: imdb
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - ./app:/app/app
      - ./scripts:/app/scripts
      - ./data:/app/data
    working_dir: /app

volumes:
  imdb_data: